# Generated by Django 3.2.9 on 2023-11-20 14:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='filter',
            name='languages',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.languages'),
        ),
        migrations.AddField(
            model_name='course',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.category'),
        ),
        migrations.AddField(
            model_name='course',
            name='filter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.filter'),
        ),
        migrations.AddField(
            model_name='course',
            name='languages',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.languages'),
        ),
        migrations.AddField(
            model_name='comments',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.course'),
        ),
        migrations.AddField(
            model_name='certificate',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.course'),
        ),
    ]
